version: '3.7'
services:
  mongo:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    expose:
      - 27017
  prime-numbers-service:
    build:
      context: ./prime-numbers-service
      cache_from:
        - raestio/prime-numbers-service:latest
    image: raestio/prime-numbers-service:latest
    restart: always
    expose:
      - 8080
  data-management-service:
    build:
      context: ./data-management-service
      cache_from:
        - raestio/data-management-service:latest
    image: raestio/data-management-service:latest
    restart: always
    expose:
      - 8080
  frontend-demo-app:
    build:
      context: ./frontend-demo-app
      dockerfile: Dockerfile
      cache_from:
        - raestio/frontend-demo-app:latest
    image: raestio/frontend-demo-app:latest
    restart: always
    volumes:
      - ./frontend-demo-app:/app
      - /app/node_modules/
    expose:
      - 3000
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: raestio/proxy:latest
    restart: always
    ports:
      - 80:80