apiVersion: v1
kind: Service
metadata:
  name: prime-numbers-service-cluster-ip
spec:
  type: ClusterIP
  selector:
    component: prime-numbers-service
  ports:
    - port: 8080
      targetPort: 8080